### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by asadmehdi785** [trixiemp/prj-rev-bwfs-dasmoto#3]
Excellent work on this project! Your HTML and CSS code was clean and readable, and you also did a good job keeping the contents of your project organized. In addition, you followed the specification very closely, and there weren't any major differences between the spec and your website that I wanted to point out. Outstanding job overall!

I hope you enjoy the rest of the course!

Grade: **Exceeds expectations**

**Comment by trixiemp** [comment]
Thank you for your feedback!

**Comment by asadmehdi785** [comment]
You're very welcome!
